name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
      - master
  pull_request:

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
           with:
          # go-version: 1.19
          go-version-file: go.mod
          # The builtin cache feature ensures that installing golangci-lint
          # is consistently fast.
          cache: true
          cache-dependency-path: go.sum
      - name: Install golangci-lint
        # Install golangci-lint from source instead of using
        # golangci-lint-action to ensure the golangci-lint binary is built with
        # the same Go version we're targeting.
        # Avoids incompatibility issues such as:
        # - https://github.com/golangci/golangci-lint/issues/2922
        # - https://github.com/golangci/golangci-lint/issues/2673
        # - https://github.com/golangci/golangci-lint-action/issues/442
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.47.3
      - name: Run golangci-lint
        run: golangci-lint run --version --verbose --out-format=github-actions