name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
      - master
  pull_request:

permissions:
  contents: read

jobs:
  golangci:
    strategy:
      matrix:
        go-version: [1.x]
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.43